name: Desarrollo Web Integral

on: 
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Desarrollo Web Integral
        run:  echo "Desarrollo Web Integral"
      
      - name: Touch File
        run: touch prueba.txt

      - name: Set Texto
        run:  echo "Bienvenidos" >> prueba.txt
      
      - name: Desplegar contenido
        run:  cat prueba.txt

  otro:
    runs-on: ubuntu-latest
    needs:  hello

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Desarrollo Web Integral
        run:  ls -al
